<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="7" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="61" started-at="2014-09-08T21:19:04Z" finished-at="2014-09-08T21:19:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="61" started-at="2014-09-08T21:19:04Z" finished-at="2014-09-08T21:19:05Z">
      <class name="com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest">
        <test-method status="PASS" signature="testSumEmptyString()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest@1fb59afc]" name="testSumEmptyString" duration-ms="13" started-at="2014-09-09T00:19:04Z" finished-at="2014-09-09T00:19:05Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[One of the strings is empty]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: One of the strings is empty
	at com.sirma.itt.javacourse.intro.numbers.NumbersSummator.sumLargeNumbers(NumbersSummator.java:37)
	at com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest.testSumEmptyString(NumbersSummatorTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumEmptyString -->
        <test-method status="PASS" signature="testSumLargeNumbersInvalidNumbers()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest@1fb59afc]" name="testSumLargeNumbersInvalidNumbers" duration-ms="2" started-at="2014-09-09T00:19:05Z" finished-at="2014-09-09T00:19:05Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[The number format is not valid!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: The number format is not valid!
	at com.sirma.itt.javacourse.intro.numbers.NumbersSummator.sumLargeNumbers(NumbersSummator.java:41)
	at com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest.testSumLargeNumbersInvalidNumbers(NumbersSummatorTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumLargeNumbersInvalidNumbers -->
        <test-method status="PASS" signature="testSumLargeNumbersNegativeNumbers()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest@1fb59afc]" name="testSumLargeNumbersNegativeNumbers" duration-ms="1" started-at="2014-09-09T00:19:05Z" finished-at="2014-09-09T00:19:05Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[The number format is not valid!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: The number format is not valid!
	at com.sirma.itt.javacourse.intro.numbers.NumbersSummator.sumLargeNumbers(NumbersSummator.java:41)
	at com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest.testSumLargeNumbersNegativeNumbers(NumbersSummatorTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumLargeNumbersNegativeNumbers -->
        <test-method status="PASS" signature="testSumLargeNumbersNormalNumbers()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest@1fb59afc]" name="testSumLargeNumbersNormalNumbers" duration-ms="5" started-at="2014-09-09T00:19:05Z" finished-at="2014-09-09T00:19:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumLargeNumbersNormalNumbers -->
        <test-method status="PASS" signature="testSumLargeNumbersOneZero()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest@1fb59afc]" name="testSumLargeNumbersOneZero" duration-ms="2" started-at="2014-09-09T00:19:05Z" finished-at="2014-09-09T00:19:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumLargeNumbersOneZero -->
        <test-method status="PASS" signature="testSumLargeNumbersTwoZeros()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest@1fb59afc]" name="testSumLargeNumbersTwoZeros" duration-ms="1" started-at="2014-09-09T00:19:05Z" finished-at="2014-09-09T00:19:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumLargeNumbersTwoZeros -->
        <test-method status="PASS" signature="testSumNullString()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest@1fb59afc]" name="testSumNullString" duration-ms="0" started-at="2014-09-09T00:19:05Z" finished-at="2014-09-09T00:19:05Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[One of the strings is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: One of the strings is null
	at com.sirma.itt.javacourse.intro.numbers.NumbersSummator.sumLargeNumbers(NumbersSummator.java:33)
	at com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest.testSumNullString(NumbersSummatorTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumNullString -->
      </class> <!-- com.sirma.itt.javacourse.intro.numbers.NumbersSummatorTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
