<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="5" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46" started-at="2014-07-27T21:30:44Z" finished-at="2014-07-27T21:30:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="46" started-at="2014-07-27T21:30:44Z" finished-at="2014-07-27T21:30:44Z">
      <class name="com.sirma.itt.javacourse.intro.numbers.SummatorLargeNumbersTest">
        <test-method status="PASS" signature="testSumLargeNumbersInvalidNumbers()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.SummatorLargeNumbersTest@10c13a99]" name="testSumLargeNumbersInvalidNumbers" duration-ms="14" started-at="2014-07-28T00:30:44Z" finished-at="2014-07-28T00:30:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[The number format is not valid!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: The number format is not valid!
	at com.sirma.itt.javacourse.intro.numbers.SummatorLargeNumbers.sumLargeNumbers(SummatorLargeNumbers.java:32)
	at com.sirma.itt.javacourse.intro.numbers.SummatorLargeNumbersTest.testSumLargeNumbersInvalidNumbers(SummatorLargeNumbersTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumLargeNumbersInvalidNumbers -->
        <test-method status="PASS" signature="testSumLargeNumbersNegativeNumbers()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.SummatorLargeNumbersTest@10c13a99]" name="testSumLargeNumbersNegativeNumbers" duration-ms="0" started-at="2014-07-28T00:30:44Z" finished-at="2014-07-28T00:30:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[The number format is not valid!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: The number format is not valid!
	at com.sirma.itt.javacourse.intro.numbers.SummatorLargeNumbers.sumLargeNumbers(SummatorLargeNumbers.java:32)
	at com.sirma.itt.javacourse.intro.numbers.SummatorLargeNumbersTest.testSumLargeNumbersNegativeNumbers(SummatorLargeNumbersTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumLargeNumbersNegativeNumbers -->
        <test-method status="PASS" signature="testSumLargeNumbersNormalNumbers()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.SummatorLargeNumbersTest@10c13a99]" name="testSumLargeNumbersNormalNumbers" duration-ms="5" started-at="2014-07-28T00:30:44Z" finished-at="2014-07-28T00:30:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumLargeNumbersNormalNumbers -->
        <test-method status="PASS" signature="testSumLargeNumbersOneZero()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.SummatorLargeNumbersTest@10c13a99]" name="testSumLargeNumbersOneZero" duration-ms="2" started-at="2014-07-28T00:30:44Z" finished-at="2014-07-28T00:30:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumLargeNumbersOneZero -->
        <test-method status="PASS" signature="testSumLargeNumbersTwoZeros()[pri:0, instance:com.sirma.itt.javacourse.intro.numbers.SummatorLargeNumbersTest@10c13a99]" name="testSumLargeNumbersTwoZeros" duration-ms="2" started-at="2014-07-28T00:30:44Z" finished-at="2014-07-28T00:30:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSumLargeNumbersTwoZeros -->
      </class> <!-- com.sirma.itt.javacourse.intro.numbers.SummatorLargeNumbersTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
